### ISSUE TITLE
How to find total peaks in a sample?

### ISSUE THREAD

**Issue by kandarpRJ** [scottzijiezhang/RADAR#3]
Hi,

I need a list of all the peaks/bins passing a threshold and their corresponding genome coordinates. I get this information after running diffIP and results for DM sites but I also need a list of per sample peaks number which are not differential. Is there a way to get this information?

TIA

regards,
Kandarp

**Comment by scottzijiezhang** [comment]
Hi Dandarp,
In current implementation, I didn't process the non-significant bins into genomic coordinate for exportable result. 
The major reason is that these bins passing filter but not significantly different across samples contain real m6A peaks and non-peaks (the filtering criterial only focus on sufficiency of reads but not really test the enrichment). We assume non-peaks will not be consistently different across group in m6A-IP experiment. But for non-significant bins, further test is needed to determine if it is a peak (significantly enriched site).
Because there are several packages available for peak calling, we didn't further implement this in RADAR. You may use peak calling package such as exomePeak to get a set of peaks.

Zijie
